apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensds-pvc-restore-file
spec:
  storageClassName: nginx-sc-file
  dataSource:
    name: new-snapshot-demo
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
